### ISSUE TITLE
Support for creating buttons in a Storyboard

### ISSUE THREAD

**Issue by ndmeiri** [Famolus/HTPressableButton#41]

**Comment by ndmeiri** [comment]
Currently, I have to follow these steps to configure/use HTPressableButton in a storyboard:
1. Drag a UIButton out onto the Storyboard.
2. Set its "Type" to Custom in the Attributes Inspector.
3. In code, usually viewWillAppear(), configure the properties that aren't "reachable" from the Storyboard such as cornerRadius, buttonColor, shadowColor.

It would be helpful to make the class IBDesignable and its properties IBInspectable.

**Comment by robertherdzik** [comment]
Now for my purposes I update lib by adding initWithCoder method, it works fine with storyboards now, but I thing that this storyboard option should be added natively to lib.
Best reg! btw. you are doing a great job!
